### ISSUE TITLE
Time-of-day Graphs

### ISSUE THREAD

**Issue by allenkaplan** [Inder-Dhillon/Toronto-Accidents-As-A-Network#2]
- [ ] Day
- [ ] Night
- [ ] Rush hour (7-9/10 & 4/5-7)

**Comment by harruup** [comment]
Rush Hour in Toronto (from wikipidea): 6:30-9:30am, 3-7pm
TIME column in dataset gives the exact time
For now the day time is 7am-7pm, night 7pm-7am but we can change it to whatever

**Comment by allenkaplan** [comment]
@harruup are the graphs able to print?
